// Mocks generated by Mockito 5.4.6 from annotations
// in linkforty_flutter/test/deeplink/deeplink_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:linkforty_flutter/fingerprint/device_fingerprint.dart' as _i3;
import 'package:linkforty_flutter/fingerprint/fingerprint_collector.dart'
    as _i7;
import 'package:linkforty_flutter/network/http_method.dart' as _i5;
import 'package:linkforty_flutter/network/network_manager.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeviceFingerprint_1 extends _i1.SmartFake
    implements _i3.DeviceFingerprint {
  _FakeDeviceFingerprint_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NetworkManagerProtocol].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkManagerProtocol extends _i1.Mock
    implements _i4.NetworkManagerProtocol {
  MockNetworkManagerProtocol() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<T> request<T>({
    required String? endpoint,
    required _i5.HttpMethod? method,
    Object? body,
    Map<String, String>? headers,
    required T Function(Map<String, dynamic>)? fromJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [],
          {
            #endpoint: endpoint,
            #method: method,
            #body: body,
            #headers: headers,
            #fromJson: fromJson,
          },
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #request,
                  [],
                  {
                    #endpoint: endpoint,
                    #method: method,
                    #body: body,
                    #headers: headers,
                    #fromJson: fromJson,
                  },
                ),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_0<T>(
              this,
              Invocation.method(
                #request,
                [],
                {
                  #endpoint: endpoint,
                  #method: method,
                  #body: body,
                  #headers: headers,
                  #fromJson: fromJson,
                },
              ),
            ),
      ) as _i2.Future<T>);
}

/// A class which mocks [FingerprintCollectorProtocol].
///
/// See the documentation for Mockito's code generation for more information.
class MockFingerprintCollectorProtocol extends _i1.Mock
    implements _i7.FingerprintCollectorProtocol {
  MockFingerprintCollectorProtocol() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_i3.DeviceFingerprint> collectFingerprint({
    required int? attributionWindowHours,
    String? deviceId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #collectFingerprint,
          [],
          {
            #attributionWindowHours: attributionWindowHours,
            #deviceId: deviceId,
          },
        ),
        returnValue:
            _i2.Future<_i3.DeviceFingerprint>.value(_FakeDeviceFingerprint_1(
          this,
          Invocation.method(
            #collectFingerprint,
            [],
            {
              #attributionWindowHours: attributionWindowHours,
              #deviceId: deviceId,
            },
          ),
        )),
      ) as _i2.Future<_i3.DeviceFingerprint>);
}
