// Mocks generated by Mockito 5.4.6 from annotations
// in linkforty_flutter/test/events/event_tracker_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:linkforty_flutter/events/event_queue.dart' as _i9;
import 'package:linkforty_flutter/models/deep_link_data.dart' as _i7;
import 'package:linkforty_flutter/models/event_request.dart' as _i8;
import 'package:linkforty_flutter/network/http_method.dart' as _i4;
import 'package:linkforty_flutter/network/network_manager.dart' as _i3;
import 'package:linkforty_flutter/storage/storage_manager.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NetworkManagerProtocol].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkManagerProtocol extends _i1.Mock
    implements _i3.NetworkManagerProtocol {
  MockNetworkManagerProtocol() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<T> request<T>({
    required String? endpoint,
    required _i4.HttpMethod? method,
    Object? body,
    Map<String, String>? headers,
    required T Function(Map<String, dynamic>)? fromJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [],
          {
            #endpoint: endpoint,
            #method: method,
            #body: body,
            #headers: headers,
            #fromJson: fromJson,
          },
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #request,
                  [],
                  {
                    #endpoint: endpoint,
                    #method: method,
                    #body: body,
                    #headers: headers,
                    #fromJson: fromJson,
                  },
                ),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_0<T>(
              this,
              Invocation.method(
                #request,
                [],
                {
                  #endpoint: endpoint,
                  #method: method,
                  #body: body,
                  #headers: headers,
                  #fromJson: fromJson,
                },
              ),
            ),
      ) as _i2.Future<T>);
}

/// A class which mocks [StorageManagerProtocol].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageManagerProtocol extends _i1.Mock
    implements _i6.StorageManagerProtocol {
  MockStorageManagerProtocol() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<bool> saveInstallId(String? installId) => (super.noSuchMethod(
        Invocation.method(
          #saveInstallId,
          [installId],
        ),
        returnValue: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);

  @override
  _i2.Future<bool> saveInstallData(_i7.DeepLinkData? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveInstallData,
          [data],
        ),
        returnValue: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);

  @override
  bool isFirstLaunch() => (super.noSuchMethod(
        Invocation.method(
          #isFirstLaunch,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.Future<bool> setHasLaunched() => (super.noSuchMethod(
        Invocation.method(
          #setHasLaunched,
          [],
        ),
        returnValue: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);

  @override
  _i2.Future<bool> saveEventQueue(List<_i8.EventRequest>? events) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveEventQueue,
          [events],
        ),
        returnValue: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);

  @override
  List<_i8.EventRequest> loadEventQueue() => (super.noSuchMethod(
        Invocation.method(
          #loadEventQueue,
          [],
        ),
        returnValue: <_i8.EventRequest>[],
      ) as List<_i8.EventRequest>);

  @override
  _i2.Future<bool> saveAttribution(String? json) => (super.noSuchMethod(
        Invocation.method(
          #saveAttribution,
          [json],
        ),
        returnValue: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);

  @override
  _i2.Future<bool> removeAttribution() => (super.noSuchMethod(
        Invocation.method(
          #removeAttribution,
          [],
        ),
        returnValue: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);

  @override
  _i2.Future<bool> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);
}

/// A class which mocks [EventQueue].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventQueue extends _i1.Mock implements _i9.EventQueue {
  MockEventQueue() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get count => (super.noSuchMethod(
        Invocation.getter(#count),
        returnValue: 0,
      ) as int);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);

  @override
  bool get isFull => (super.noSuchMethod(
        Invocation.getter(#isFull),
        returnValue: false,
      ) as bool);

  @override
  bool enqueue(_i8.EventRequest? event) => (super.noSuchMethod(
        Invocation.method(
          #enqueue,
          [event],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<_i8.EventRequest> peek() => (super.noSuchMethod(
        Invocation.method(
          #peek,
          [],
        ),
        returnValue: <_i8.EventRequest>[],
      ) as List<_i8.EventRequest>);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
